# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WefkSafpY6u0Q6XX9fr80fLo2iVFMUOh
"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

# =========================
# LOAD DATA
# =========================

df = pd.read_csv("../data/laptop_price.csv", encoding="latin1")

# =========================
# DROP UNUSED COLUMN
# =========================

df.drop("laptop_ID", axis=1, inplace=True)

# =========================
# CLEAN DATA
# =========================

# Convert RAM
df["Ram"] = df["Ram"].str.replace("GB", "", regex=False).astype(int)

# Convert Weight
df["Weight"] = (
    df["Weight"]
    .str.replace("kg", "", regex=False)
    .astype(float)
)

# =========================
# FEATURES & TARGET
# =========================

X = df.drop("Price_euros", axis=1)
y = df["Price_euros"]

# =========================
# COLUMN TYPES
# =========================

categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()

numerical_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

# =========================
# PREPROCESSING
# =========================

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]
)

numerical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", categorical_transformer, categorical_cols),
        ("num", numerical_transformer, numerical_cols)
    ]
)

# =========================
# MODEL PIPELINE
# =========================

model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", RandomForestRegressor(
            n_estimators=200,
            random_state=42
        ))
    ]
)

# =========================
# TRAIN TEST SPLIT
# =========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# =========================
# TRAIN MODEL
# =========================

model.fit(X_train, y_train)

# =========================
# EVALUATE
# =========================

predictions = model.predict(X_test)

r2 = r2_score(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)

print(f"R2 Score: {r2:.4f}")
print(f"MAE: {mae:.2f} Euros")

# =========================
# SAVE MODEL
# =========================

joblib.dump(model, "./laptop_price_model.pkl")

print("Model saved successfully.")